layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Cycle.js
    web_url: https://cycle.js.org/
    image_url: https://cycle.js.org/img/cyclejs_logo.svg

  - name: Rx.js
    web_url: https://rxjs-dev.firebaseapp.com/
    image_url: https://rxjs-dev.firebaseapp.com/generated/images/marketing/home/Rx_Logo-512-512.png

  - name: Neumorphism
    web_url: https://neumorphism.io/

theme: jekyll-theme-architect
